sudo: false
language: ruby
services:
  - docker
before_install:
  - git clone --depth 1 https://github.com/seiferma/Docker_BuildUtils.git /tmp/BuildUtils
  - . /tmp/BuildUtils/travisSetup.sh
script:
  - travisBuildDockerhub.sh
deploy:
  provider: script
  script: travisDeployDockerhub.sh
  on:
    branch: master
env:
  global: 
    - IMAGE_NAME=seiferma/samba
    - secure: "NDcKLeH5up8TlRneakm0IR1E/leA/lALnkmrx4IifwlBKJOv+9eFXhNjMxb3P6v1stnHC9A3LZAhb3H4u7lWj2329ChuV5OZBukY3gby8Ow8WS9X7nk6pFwL1RAU7mpRFiYsWKWj8QWHoRi2ZVMH5nxt+5Nt2y0WGf6sE6ssT7e902Avk3+7Hr3nFuXP1xxcZxVdG8U+knZMTChuABMKfYfj5ajit/rKyzP6pV3DcpTJxr9H8HW58VgRe29HZdgz+2HlFkgZn9a0MtJ+RPKw4zohHrX8P5AJIKbBtZeJ+G1K5VEdScY0rrZX5adHB1NurBN4SWBHbnVaBS1c8R2VSDtxswWDcUfL9huNFUNXa1gCttiuubAgg6Yysh6fABICp14eqrUcZtDIfhlDu7XNtxHF6CxlNsHbl3VtFeJ0TG2Ycw7b84tyBl8I2a5TVPWtGeP+egQSwhnwo1JsES1FG5C04VBc4m4SLYcuwYIkddBKTE0saXaW6JpyMlOffXunJm0GUZiNof/22p6STrAt84H7eLT4FbCiLvxHPimnF4y4QokGg70JODIIUjNym6EkKnCLKU4XS1d7fNj4cVw21SAiKP6YLQA72C+W1Qaapa7lzuD/aawf39ZGIbHzo0LIizRzcTwI7al04RUPyN1qQQ+HX/FT7Imc7Y7m7EnBw9w="